
package conversor.gui;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.border.Border;

/**
 *
 * @author leonardo J. Olmedo
 */
public class ConversorGUI extends javax.swing.JFrame {

    /**
     * Creates new form ConversorGUI
     */
    public ConversorGUI() {
        initComponents();
    }
    
    Border bordeRojo = BorderFactory.createLineBorder(Color.red, 2);
    Border bordeNegro = BorderFactory.createLineBorder(Color.black, 1);
    
    public void setMonedas(String opciones[]){
        this.txtUnidadOrigen.removeAllItems();
        this.txtUnidadDestino.removeAllItems();
        for (String opcion : opciones) {
            this.txtUnidadOrigen.addItem(opcion);
            this.txtUnidadDestino.addItem(opcion);
        }
    }
    
    public void setAccionMoneda (ActionListener accionMmoneda){
        this.btnMoneda.addActionListener(accionMmoneda);
    }
    
    public void setAccionLongitud (ActionListener accionLongitud){
        this.btnLongitud.addActionListener(accionLongitud);
    }
    
    public void setAccionTemperatura (ActionListener accionTemperatura){
        this.btnTemperatura.addActionListener(accionTemperatura);
    }
    
    public void setAccionConvertir (ActionListener accionConvertir){
        this.btnConvertir.addActionListener(accionConvertir);
    }
    
    public void setTitulo(String titulo){
        this.lblTitulo.setText(titulo);
    }
    
    public void setUnidad(String unidad){
        this.lblUnidadOrigen.setText(unidad);
        this.lblUnidadDestino.setText(unidad);
    }
    
    public String getTxtMonto(){
        return this.txtMonto.getText();
    }
    
    public void setTxtMonto(String monto){
        this.txtMonto.setText(monto);
    }
    
    public void setTxtCambio(String cambio){
        this.txtCambio.setText(cambio);
    }
    
    public int getTxtUnidadOrigen(){
        return this.txtUnidadOrigen.getSelectedIndex();
    }
    
    public int getTxtUnidadDestino(){
        return this.txtUnidadDestino.getSelectedIndex();
    }
    
    public void alerta(String mensaje){
        this.txtMensaje.setText(mensaje);
        if(mensaje == ""){
            this.txtMonto.setBorder(this.bordeNegro);
        }
        else{
            this.txtMensaje.setForeground(Color.red);
            this.txtMonto.setBorder(this.bordeRojo);
        }
    }
    
    public void resetGUI(String titulo, String unidad, String monedas[], String txtCambio, String txtMonto){
        this.setTitulo(titulo);
        this.setUnidad(unidad);
        this.setMonedas(monedas);
        this.txtCambio.setText(txtCambio);
        this.txtMonto.setText(txtMonto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        lblValor = new javax.swing.JLabel();
        txtUnidadOrigen = new javax.swing.JComboBox<>();
        lblUnidadOrigen = new javax.swing.JLabel();
        txtCambio = new javax.swing.JTextField();
        lblCambio = new javax.swing.JLabel();
        txtUnidadDestino = new javax.swing.JComboBox<>();
        lblUnidadDestino = new javax.swing.JLabel();
        btnConvertir = new javax.swing.JButton();
        txtMensaje = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btnMoneda = new javax.swing.JButton();
        btnLongitud = new javax.swing.JButton();
        btnTemperatura = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Cantarell", 0, 48)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Coversor de monedas");

        txtMonto.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        txtMonto.setText("1");
        txtMonto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblValor.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        lblValor.setText("Valor:");

        txtUnidadOrigen.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        txtUnidadOrigen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblUnidadOrigen.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        lblUnidadOrigen.setText("Unidad:");

        txtCambio.setEditable(false);
        txtCambio.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        txtCambio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblCambio.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        lblCambio.setText("equivalencia: ");

        txtUnidadDestino.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        txtUnidadDestino.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblUnidadDestino.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        lblUnidadDestino.setText("Unidad");

        btnConvertir.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        btnConvertir.setText("Convertir");

        txtMensaje.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N

        btnMoneda.setText("Monedas");

        btnLongitud.setText("Longitud");

        btnTemperatura.setText("Temperatura");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblUnidadOrigen)
                            .addComponent(lblValor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUnidadOrigen, 0, 175, Short.MAX_VALUE)
                            .addComponent(txtMonto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCambio)
                            .addComponent(lblUnidadDestino))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUnidadDestino, 0, 175, Short.MAX_VALUE)
                            .addComponent(txtCambio)))
                    .addComponent(jSeparator2)
                    .addComponent(txtMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLongitud, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(398, 398, 398)
                .addComponent(btnConvertir)
                .addContainerGap(405, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(15, 15, 15)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMoneda)
                    .addComponent(btnLongitud)
                    .addComponent(btnTemperatura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblValor)
                            .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUnidadOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUnidadOrigen)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCambio)
                            .addComponent(txtCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUnidadDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUnidadDestino))))
                .addGap(37, 37, 37)
                .addComponent(btnConvertir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Copyright 2023, Leonardo J. Olmedo ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    /**
     * @param args the command line arguments
     */

	//el método main fue removido para utilizar la clase conversor como controlador de la lógica del programa
    
    /*public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConversorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConversorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConversorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConversorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConversorGUI().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConvertir;
    private javax.swing.JButton btnLongitud;
    private javax.swing.JButton btnMoneda;
    private javax.swing.JButton btnTemperatura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblCambio;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUnidadDestino;
    private javax.swing.JLabel lblUnidadOrigen;
    private javax.swing.JLabel lblValor;
    private javax.swing.JTextField txtCambio;
    private javax.swing.JLabel txtMensaje;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JComboBox<String> txtUnidadDestino;
    private javax.swing.JComboBox<String> txtUnidadOrigen;
    // End of variables declaration//GEN-END:variables
}
